# Original: About Divvun Manager
aboutApp: About Divvun Manager

# Original: All Repositories
allRepositories: All Repositories

# Original: Alpha
alpha: Alpha

# Original: Help
appHelp: Help

# Original: Divvun Manager
appName: Divvun Manager

# Original: Divvun Manager v{version} is now available. It is highly recommended that you update as soon as possible. Update now?
appUpdateBody: >-
  Divvun Manager v{version} is now available. It is highly recommended that you
  update as soon as possible. Update now?

# Original: Divvun Manager Update Available
appUpdateTitle: Divvun Manager Update Available

# Original: Beta
beta: Beta

# Original: Bring All to Front
bringAllToFront: Bring All to Front

# Original: Cancel
cancel: Cancel

# Original: Are you sure you want to cancel all downloads?
cancelDownloadsBody: Are you sure you want to cancel all downloads?

# Original: Cancel Downloads
cancelDownloadsTitle: Cancel Downloads

# Original: Canceling...
cancelling: Canceling...

# Original: Category
category: Category

# Original: Channel
channel: Channel

# Original: Check For Updates...
checkForUpdates: Check For Updates...

# Original: Completed
completed: Completed

# Original: Copy
copy: Copy

# Original: Do you wish to send a crash report to the developers? No personal or private information is sent. (Recommended)
crashReportBody: >-
  Do you wish to send a crash report to the developers? No personal or private
  information is sent. (Recommended)

# Original: Cut
cut: Cut

# Original: Daily
daily: Daily

# Original: Delete
delete: Delete

# Original: Error 😞
downloadError: "Error \U0001F61E"

# Original: Downloaded
downloaded: Downloaded

# Original: Downloading...
downloading: Downloading...

# Original: Edit
edit: Edit

# Original: Error
error: Error

# Original: An error occurring during installation.
errorDuringInstallation: An error occurring during installation.

# Original: Error: Invalid Version
errorInvalidVersion: 'Error: Invalid Version'

# Original: Error: No Installer
errorNoInstaller: 'Error: No Installer'

# Original: Error: Unknown Item
errorUnknownPackage: 'Error: Unknown Item'

# Original: Every 4 Weeks
everyFourWeeks: Every 4 Weeks

# Original: Every 2 Weeks
everyTwoWeeks: Every 2 Weeks

# Original: Exit
exit: Exit

# Original: Finish
finish: Finish

# Original: Help
help: Help

# Original: Hide Divvun Manager
hideApp: Hide Divvun Manager

# Original: Hide Others
hideOthers: Hide Others

# Original: Install
install: Install

# Original: Install {count} Items
installNPackages: 'Install {count} Items'

# Original: Install (System)
installSystem: Install (System)

# Original: Install/Uninstall {count} Items
installUninstallNPackages: 'Install/Uninstall {count} Items'

# Original: Install (User)
installUser: Install (User)

# Original: Installed
installed: Installed

# Original: Installing {name} {version}...
installingPackage: 'Installing {name} {version}...'

# Original: Installing/Uninstalling
installingUninstalling: Installing/Uninstalling

# Original: Interface Language
interfaceLanguage: Interface Language

# Original: Please ensure that the URL begins with "https" and try again.
invalidUrlBody: Please ensure that the URL begins with "https" and try again.

# Original: The provided URL is invalid.
invalidUrlTitle: The provided URL is invalid.

# Original: Language
language: Language

# Original: Loading...
loading: Loading...

# Original: Minimize
minimize: Minimize

# Original: {count} items remaining.
nItemsRemaining: '{count} items remaining.'

# Original: {count} Updates Available
nUpdatesAvailable: '{count} Updates Available'

# Original: Never
never: Never

# Original: Next update check at: {date}
nextUpdateDue: 'Next update check at: {date}'

# Original: Nightly
nightly: Nightly

# Original: No Items Selected
noPackagesSelected: No Items Selected

# Original: No new updates were found.
noUpdatesBody: No new updates were found.

# Original: No Updates
noUpdatesTitle: No Updates

# Original: --
notApplicable: '--'

# Original: Not Installed
notInstalled: Not Installed

# Original: OK
ok: OK

# Original: Open Divvun Manager
openPackageManager: Open Divvun Manager

# Original: Open Settings…
openSettings: Open Settings…

# Original: Paste
paste: Paste

# Original: Paste and Match Style
pasteAndMatchStyle: Paste and Match Style

# Original: Preferences…
preferences: Preferences…

# Original: You may now close this window, or return to the main screen.
processCompletedBody: 'You may now close this window, or return to the main screen.'

# Original: Done!
processCompletedTitle: Done!

# Original: Queued
queued: Queued

# Original: Quit Divvun Manager
quitApp: Quit Divvun Manager

# Original: Redo
redo: Redo

# Original: Remind Me Later
remindMeLater: Remind Me Later

# Original: Are you sure you wish to remove this repository?
removeRepoBody: Are you sure you wish to remove this repository?

# Original: This will remove the selected repository.
removeRepoTitle: This will remove the selected repository.

# Original: Repositories
repositories: Repositories

# Original: Repository
repository: Repository

# Original: Repository Error
repositoryError: Repository Error

# Original: There was an error while opening the repository:
# 
# {message}
repositoryErrorBody: |-
  There was an error while opening the repository:

  {message}

# Original: Restart Later
restartLater: Restart Later

# Original: Restart Now
restartNow: Restart Now

# Original: It is highly recommended that you restart your computer in order for some changes to take effect.
restartRequiredBody: >-
  It is highly recommended that you restart your computer in order for some
  changes to take effect.

# Original: Time to reboot!
restartRequiredTitle: Time to reboot!

# Original: Restart the app for language changes to take effect.
restartTheAppForLanguageChanges: Restart the app for language changes to take effect.

# Original: Save
save: Save

# Original: Select All
selectAll: Select All

# Original: Select Repository
selectRepository: Select Repository

# Original: Services
services: Services

# Original: Settings
settings: Settings

# Original: Show All
showAll: Show All

# Original: Skip These Updates
skipTheseUpdates: Skip These Updates

# Original: Sort by…
sortBy: Sort by…

# Original: Stable
stable: Stable

# Original: Starting...
starting: Starting...

# Original: Default Language
systemLocale: Default Language

# Original: There are {count} updates available!
thereAreNUpdatesAvailable: 'There are {count} updates available!'

# Original: To get started, add a repository in Settings.
toGetStartedAddARepoInSettings: 'To get started, add a repository in Settings.'

# Original: Undo
undo: Undo

# Original: Uninstall
uninstall: Uninstall

# Original: Uninstall {count} Items
uninstallNPackages: 'Uninstall {count} Items'

# Original: Uninstalling {name} {version}...
uninstallingPackage: 'Uninstalling {name} {version}...'

# Original: Update
update: Update

# Original: Update Available
updateAvailable: Update Available

# Original: Update Channel
updateChannel: Update Channel

# Original: Update Frequency
updateFrequency: Update Frequency

# Original: Update (System)
updateSystem: Update (System)

# Original: Update (User)
updateUser: Update (User)

# Original: URL
url: URL

# Original: {description} (User)
userDescription: '{description} (User)'

# Original: Version Skipped
versionSkipped: Version Skipped

# Original: Waiting for process to finish...
waitingForCompletion: Waiting for process to finish...

# Original: Weekly
weekly: Weekly

# Original: Window
window: Window

# Original: Would you like to download them now?
wouldYouLikeToDownloadThemNow: Would you like to download them now?

# Original: Zoom
zoom: Zoom

# Original: Connecting...
connecting: Connecting...

# Original: This is taking too long
takingTooLong: This is taking too long

# Original: Failed communicating to the language index service. Please restart the app and try again. If that does not help, try reinstalling Divvun Manager.
connectionFailed: Failed communicating to the language index service. Please restart the app and try again. If that does not help, try reinstalling Divvun Manager.
