#!/bin/sh
set -ex

PLIST_FILE="no.divvun.pahkatd.plist"

# Uninstall Divvun Installer 1.0
if [[ -e "/Applications/Divvun Installer.app" ]]; then
  rm -rf "/Applications/Divvun Installer.app"
  pkgutil --forget no.divvun.Pahkat
  rm -f /Library/LaunchDaemons/no.divvun.PahkatAdminService.plist
  rm -f /Library/PrivilegedHelperTools/no.divvun.PahkatAdminService
fi

rm -f "/Library/LaunchDaemons/$PLIST_FILE";
cp "$PLIST_FILE" "/Library/LaunchDaemons/$PLIST_FILE";
/bin/launchctl load -w "/Library/LaunchDaemons/$PLIST_FILE";

# Create log directory
mkdir -p /Library/Logs/Pahkat
su "$USER" -c "mkdir -p ~/Library/Logs/MacDivvun"

if [[ ! $COMMAND_LINE_INSTALL ]]; then
  for i in $(seq 1 5); do su "$USER" -c "open /Applications/Divvun\ Manager.app" && s=0 && break || s=$? && sleep 1; done; (exit $s)
fi
